pluginManagement {
    repositories {
        maven { url = 'https://neoforged.net' }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'OfflineLanPlay-parent'

include 'neoforge-1.21'
include 'neoforge-26.1-26.1.2'
include 'neoforge-26.2'
